public enum TokenEnum {
    COMMA, COLON, SEMI, LPAREN, RPAREN, LBRACK, RBRACK,
    LBRACE, RBRACE, PERIOD, PLUS, MINUS, MULT, DIV, EQ,
    NEQ, LESSER, GREATER, LESSEREQ, GREATEREQ, AND, OR,
    ASSIGN, ARRAY, RECORD, BREAK, DO, ELSE, FOR, FUNC, IF, IN, LET, OF, THEN, TO,
    TYPE, VAR, WHILE, ENDIF, BEGIN, END, ENDDO, ID, INTLIT, FLOATLIT, INT, FLOAT,
    RETURN, ENDOFINPUT
}

